### ISSUE TITLE
Fail to instsall for Visual Studio 2019

### ISSUE THREAD

**Issue by sgkoishi** [BigEggTools/PowerMode#9]
VS is showing a Dependency Alert said "Visual Studio MPF 15.0" is missing. 
![image](https://user-images.githubusercontent.com/9637711/55703759-5901db00-598f-11e9-84f3-6ec55bec6d51.png)

I saw this dependency in the manifest, but I'm not sure if it is necessary or I can just remove it from the list. Do I need to install something to fix it?
https://github.com/BigEggTools/PowerMode/blob/34cb6a1ee97b996bdd63f11853a3490b482d3404/PowerMode/source.extension.vsixmanifest#L18

**Comment by BigEgg** [comment]
For this I think that because this extension is build based on Visual Studio 2017, that why it need this. 
by following this article: [How to upgrade extensions to support Visual Studio 2019](https://madskristensen.net/blog/how-to-upgrade-extensions-to-support-visual-studio-2019/), I didn't update the dependency so that might cause this error. 

It might works, otherwise, let me dig more on this

**Comment by BigEgg** [comment]
Find the error, the version for that dependency is hard coded with 15.0, should update that line to fix it.

Based on https://stackoverflow.com/questions/53652152/visual-studio-2019-mpf-15-0-is-missing and https://madskristensen.net/blog/how-to-upgrade-extensions-to-support-visual-studio-2019/ these 2 links, that will fix your problem

**Comment by BigEgg** [comment]
pushed a new version for fix this. Please let me know if this still happened in your machine

**Comment by sgkoishi** [comment]
Thanks for fixing.
